### ISSUE TITLE
NPOI Reference Problem

### ISSUE THREAD

**Issue by mohSalah66** [nissl-lab/toxy#10]
When i run the test [TestParseTextFromWord] in [Word2003ParserTest] i get the flowing exception

System.IO.FileLoadException : Could not load file or assembly 'NPOI, Version=2.1.3.1, Culture=neutral, PublicKeyToken=0df73ec7942b34e1' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Toxy.Parsers.Word2003TextParser.Parse()
   at Toxy.Test.Word2003ParserTest.TestParseTextFromWord() in Word2003ParserTest.cs: line 18
and the NPOI referenced in the Toxy Project is NPOI Version=2.2.0.0 and it says it's need Version =2.1.3.1 what is the problem?
##

**Comment by tonyqus** [comment]
Sorry, the assembly of HWPF is not refreshed in Toxy 1.6. We will update it soon.
