### ISSUE TITLE
PDF v1.5 cannot be read

### ISSUE THREAD

**Issue by redwards510** [nissl-lab/toxy#8]
I cannot parse any newer PDF files because PDFSharp throws an error due to a bug where it cannot read >v1.5 of PDFs. Is there anything we can do to fix this? 
##

**Comment by tonyqus** [comment]
Since PDFSharp doesn't work well, we are thinking to roll back to some
library else. We will update it in the next version

2015-07-28 8:02 GMT+08:00 Ryan Edwards <notifications@github.com>:
